spring:
  h2:
    console:
      enabled: true     # H2 콘솔을 활성화 합니다.
      path: /h2-console # http://localhost:8080/h2-console URL에 접속하여 H2 콘솔에 접속 할 수 있습니다.
  jpa:
    hibernate:
      ddl-auto: update  # 서버기동시 model을 기반으로 테이블을 생성합니다. 변경사항이 있을 경우 적용 합니다.
    database-platform: org.hibernate.dialect.H2Dialect  # dialect 설정

  datasource:                         # DB 연결 정보 설정
    url: jdbc:h2:~/test;
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging.level.org.hibernate.SQL : debug           # SQL 로그레벨 설정
spring.jpa.properties.hibernate.format_sql: true  # SQL 로그 표시 할 때 보기 편하게 변형하여 표시 합니다.
